### ISSUE TITLE
v1.2.3 stuck at "checking for containers"

### ISSUE THREAD

**Issue by chriswood1001** [MichelFR/MqDockerUp#106]
Updated from v1.2.2 which worked fine to v1.2.3 where the logs don't progress past "Checking for containers...". Restarted and re-pulled the image several times but the instance won't properly boot. Reverting back to v1.2.2 works fine.

```
2023-08-01T02:21:04.760142842Z Starting MqDockerUp V1.2.3 ... 
2023-08-01T02:21:04.760144330Z 
2023-08-01T02:21:04.995316420Z 01.08.2023 02:21:04 [info] 	Connected to the database.
2023-08-01T02:21:05.002667605Z 01.08.2023 02:21:05 [info] 	MQTT client successfully connected
2023-08-01T02:21:05.004141130Z 01.08.2023 02:21:05 [info] 	Checking for removed containers...
2023-08-01T02:21:05.017102184Z 01.08.2023 02:21:05 [info] 	Database initialized successfully
2023-08-01T02:21:05.023413962Z 01.08.2023 02:21:05 [info] 	Checking for containers...
```

**Comment by MichelFR** [comment]
Thanks for your feedback.
Are you getting any errors?
Possibly it has something to do with the permissions of the sqlite database.

Could you please try to persist the data folder?
 -v your/path/data:/app/data/ \
 
 Or
 volumes:
      - your/path/data:/app/data/

**Comment by nanderson97651** [comment]
I ran into a similar issue when upgrading to 1.2.3.  The readme has some changes that took place with regards to the way the docker application handles configurations and the database.

I created the `config.yaml` file and mapped the following volumes in my docker-compose file.
```
- your/path/data:/app/data/ # This is required to store the data (database.db)
- your/path/config.yaml:/app/config.yaml # This is required to store the configuration file```

All of the environment variables were moved from the docker compose file to config.yaml.  This along with the line for the database seems to have resolved my issues and I'm getting update notifications through MQTT in Home Assistant again.  @MichelFR should this have been included as a breaking change in the patch notes?

**Comment by MichelFR** [comment]
Thanks for reporting back that its working successfully now.

Thats correct i should have mentioned it as a breaking change.
I rewrote the entire logic of how the handling of removed/stopped containers work, so that we have a little sqlite database now.
The database needs to be persisted else it could run into trouble.

The environment variables should still work.

I'll try to prevent breaking changes in the future.
But one is coming, im gonna rework how the handling of configuration variables is done. We will have the same environment variables like how its now. But instead of having a config.yml i'll move to a .env file using the dotenv library.
